[package]
name = "hexahop_solver"
version = "0.1.0"
edition = "2021"

[lib]
name = "hexahop_solver"
path = "rust/lib.rs"

[features]
default = ["dfs"]
bfs = []
dfs = []

[[bin]]
name = "hexahop"
path = "rust/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
validator = { version = "0.16", features = ["derive"] }
strum_macros = "0.28.0"
regex = "1.12.3"
fxhash = "0.2.1"